# -*- coding: utf-8 -*-
"""SMA EXP 03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17bydyW_QIQ0udtYlyMvQ_1V8oZ_kW_u8
"""

import pandas as pd
import numpy as np

data = pd.read_csv("/content/AYUSH_YOUTUBE.csv")

print(data.head(20))
print(data.info())

data.drop_duplicates(inplace=True)

print(data.head(20))
print(data.info())

import re

def clean_text(text):
    # Remove URLs
    text = re.sub(r'https://www.youtube.com/watch?v=', '..', text)
    text = re.sub(r'[https://www.youtube.com/watch?v=]', '', text)
    # Remove special characters and punctuation
    text = re.sub(r'[^\w\s]', '', text)
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Convert to lowercase
    text = text.lower()
    return text

# data.drop('pubdate', inplace=True, axis=1)

data.drop('to', inplace=True, axis=1)

data['author'] = data['author'].apply(clean_text)

data['link'] = data['link'].apply(clean_text)

data['authorChannelUrl'] = data['authorChannelUrl'].apply(clean_text)

import re

def clean_text(text):
    # Check if the input is a string or NaN, and return an empty string if not
    if isinstance(text, str):
        # Remove URLs
        text = re.sub(r'http\S+', '', text)
        # Remove special characters and punctuation
        text = re.sub(r'[^\w\s]', '', text)
        # Remove numbers
        text = re.sub(r'\d+', '', text)
        # Convert to lowercase
        text = text.lower()
        return text
    else:
        return ""

# Apply the modified clean_text function to the 'description' column
data['description'] = data['description'].apply(clean_text)
data['title'] = data['title'].apply(clean_text)

print(data.head(20))

print(data.info())