# -*- coding: utf-8 -*-
"""SMA EXP 6 Structure social media analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rehqsX952kW4ou2G2nOuapPWqJGcIQZ
"""

import pandas as pd
import networkx as nx

pip install fin-news

pip install network

import networkx
G=networkx.Graph()
G.add_node(1)
G.add_node(2)
G.add_node(3)
G.add_node(4)
G.add_node(5)
G.add_node(6)
G.add_node(7)
G.add_node(8)

G.add_edge(1,2)
G.add_edge(2,1)
G.add_edge(2,3)
G.add_edge(2,4)
G.add_edge(3,2)
G.add_edge(3,5)
G.add_edge(4,2)
G.add_edge(4,5)
G.add_edge(4,7)
G.add_edge(5,3)
G.add_edge(5,4)
G.add_edge(5,6)
G.add_edge(5,7)
G.add_edge(5,8)
G.add_edge(6,5)
G.add_edge(7,4)
G.add_edge(7,5)
G.add_edge(7,8)
G.add_edge(8,5)
G.add_edge(8,7)

G.edges()

nx.draw(G,with_labels=1)

nx.degree_centrality(G)

import matplotlib.pyplot as plt
import networkx as nx
G=nx.Graph()
G.add_nodes_from([1,2,3,4,5,6,7,8])
G.add_edges_from([(1, 2), (2, 3), (2, 4), (3, 5), (4, 5), (4, 7), (5, 6), (5, 7), (5, 8), (7, 8)])

nx.draw(G,with_labels=True,node_color="orange",node_size=3000,font_color="White")
plt.margins(0.2)
plt.show()

nx.degree_centrality(G)

nx.degree(G)

m_influential=nx.degree_centrality(G)
nx.eigenvector_centrality(G)

nx.betweenness_centrality(G)

list(nx.find_cliques(G))

hub_ego=nx.ego_graph(G,8)
pos=nx.spring_layout(G)
nx.draw(hub_ego,pos,node_color="lavender", node_size = 800, with_labels = True)
nx.draw_networkx_nodes( hub_ego, pos,nodelist = [8])
plt.show()

nx.density(G)

nx.has_bridges(G)

nx.closeness_centrality(G)